# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600